package com.myspace.ecommerce;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CostCalculation implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private Double cost;
	private java.lang.Integer distanceKM;
	private java.lang.Float distanceFactor;
	private java.lang.Float sWeight;
	private java.lang.Float kgFactor;
	private java.lang.Float fixedCost;

	private java.lang.Double directCost;

	private java.lang.Double nextCost;

	private java.lang.Double allCost;

	public CostCalculation() {
	}

	public java.lang.Integer getDistanceKM() {
		return this.distanceKM;
	}

	public void setDistanceKM(java.lang.Integer distanceKM) {
		this.distanceKM = distanceKM;
	}

	public java.lang.Float getDistanceFactor() {
		return this.distanceFactor;
	}

	public void setDistanceFactor(java.lang.Float distanceFactor) {
		this.distanceFactor = distanceFactor;
	}

	public java.lang.Float getsWeight() {
		return this.sWeight;
	}

	public void setsWeight(java.lang.Float sWeight) {
		this.sWeight = sWeight;
	}

	public java.lang.Float getKgFactor() {
		return this.kgFactor;
	}

	public void setKgFactor(java.lang.Float kgFactor) {
		this.kgFactor = kgFactor;
	}

	public java.lang.Float getFixedCost() {
		return this.fixedCost;
	}

	public void setFixedCost(java.lang.Float fixedCost) {
		this.fixedCost = fixedCost;
	}

	public java.lang.Double getCost() {
		return this.cost;
	}

	public void setCost(java.lang.Double cost) {
		this.cost = cost;
	}

	public java.lang.Double getDirectCost() {
		return this.directCost;
	}

	public void setDirectCost(java.lang.Double directCost) {
		this.directCost = directCost;
	}

	public java.lang.Double getNextCost() {
		return this.nextCost;
	}

	public void setNextCost(java.lang.Double nextCost) {
		this.nextCost = nextCost;
	}

	public java.lang.Double getAllCost() {
		return this.allCost;
	}

	public void setAllCost(java.lang.Double allCost) {
		this.allCost = allCost;
	}

	public CostCalculation(java.lang.Double cost, java.lang.Integer distanceKM,
			java.lang.Float distanceFactor, java.lang.Float sWeight,
			java.lang.Float kgFactor, java.lang.Float fixedCost,
			java.lang.Double directCost, java.lang.Double nextCost,
			java.lang.Double allCost) {
		this.cost = cost;
		this.distanceKM = distanceKM;
		this.distanceFactor = distanceFactor;
		this.sWeight = sWeight;
		this.kgFactor = kgFactor;
		this.fixedCost = fixedCost;
		this.directCost = directCost;
		this.nextCost = nextCost;
		this.allCost = allCost;
	}

}